#!/bin/sh
#
# Perform necessary apache_upgrade_test setup steps
# after package is installed.
#

PROGNAME=`basename $0`

error_exit()
{
  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
  exit 1
}

echo "Thank you for installing apache_upgrade_test!"

exit 0
